name: testing

on:
  push:
    branches:
      [master]
  schedule:
    - cron: '00 18 * * *'

jobs:
  testing-flow:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      -name: Install Required dependencies and software, build docke image
        uses: actions/setup-python@v2
        run: docker build . --file Dockerfile 
