name: testing

on:
  push:
    branches:
      [master]
  schedule:
    - cron: '00 18 * * *'

jobs:
  testing-flow:
    runs-on: ubuntu-latest
    steps:
      - name: Install Required dependencies and software, build docke image
        run: docker build . --file ./Dockerfile 
